### ISSUE TITLE
Crash when launching new window

### ISSUE THREAD

**Issue by scottopell** [rickbutton/workspacer#24] opened 2018-09-26 14:06 UTC
```
---------------------------
unhandled exception!
---------------------------
System.NullReferenceException: Object reference not set to an instance of an object.

   at Workspacer.Workspace.DoLayout()

   at Workspacer.WorkspaceManager.SwitchToPreviousWorkspace()

   at Workspacer.KeybindManager.DoKeyboardEvent(Keys key, KeyModifiers modifiersPressed)

   at Workspacer.KeybindManager.Hook(Int32 nCode, UIntPtr wParam, IntPtr lParam)

press ctrl-c to copy this
---------------------------
OK   
---------------------------

```

**Comment by scottopell** [comment] 2018-09-26 14:32
Getting this seemingly randomly. Can't be sure of what I'm doing when it comes up.

```
---------------------------
unhandled exception!
---------------------------
System.NullReferenceException: Object reference not set to an instance of an object.

   at Workspacer.Workspace.DoLayout()

   at Workspacer.WorkspaceManager.SwitchToPreviousWorkspace()

   at Workspacer.KeybindManager.DoKeyboardEvent(Keys key, KeyModifiers modifiersPressed)

   at Workspacer.KeybindManager.Hook(Int32 nCode, UIntPtr wParam, IntPtr lParam)

press ctrl-c to copy this
---------------------------
OK   
---------------------------

```

**Comment by scottopell** [comment] 2018-09-26 14:43
Interestingly this seems to be a non-fatal error. I can continue using workspacer as expected as long as I don't hit "OK" on this dialog

**Comment by rickbutton** [comment] 2018-12-05 01:07
@scottopell is this still happening?

**Comment by rickbutton** [comment] 2018-12-20 01:52
can't reproduce anymore, closing

**Closed by rickbutton** 2018-12-20 01:52 UTC
