### ISSUE TITLE
Exception on waking laptop from sleep

### ISSUE THREAD

**Issue by scottopell** [rickbutton/workspacer#41] opened 2018-12-17 14:51 UTC
```
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at workspacer.WorkspaceManager.InitializeWithState(WorkspaceState state, IEnumerable`1 allWindows)
   at workspacer.workspacer.Start()
   at workspacer.Program.Run()
   at workspacer.Program.Main(String[] args)
```

**Comment by rickbutton** [comment] 2018-12-20 01:52
this is likely due to the number of monitors changing, and a restart attempt fails because its not handling the lack of monitors properly.

**Comment by rickbutton** [comment] 2019-01-11 00:46
duplicate of #47

**Closed by rickbutton** 2019-01-11 00:46 UTC
Labels: bug
