### ISSUE TITLE
Run as administrator causes the tile to be lost

### ISSUE THREAD

**Issue by binick** [rickbutton/workspacer#175] opened 2021-01-23 16:12 UTC
Hi, really nice project!

When an application is start as administration privileges doesn't respect the tiling composition and it's grab as focus window.

![2021-01-23 (2)](https://user-images.githubusercontent.com/26303853/105607224-e4837080-5d9d-11eb-8ff0-28388b45e05c.png)

**Comment by sitiom** [comment] 2021-01-25 05:42
https://github.com/rickbutton/workspacer/issues/85#issuecomment-563463772

**Comment by rickbutton** [comment] 2021-02-19 17:55
duplicate of #85, closing

hwnds owned by admin processes can't be talked to by a non-admin process. the only way to get workspacer to manage admin windows is to launch workspacer as admin.

**Closed by rickbutton** 2021-02-19 17:55 UTC
